NOMES_INIMIGOS = [
 "Demonio das Sombras",
 "Espectro Devorador",
 "Golem de Gelo",
 "Harpia Voadora",
 "Esqueleto Amaldiçoado",
 "Troll Enfurecido",
 "Aberração das Trevas",
 "Fada Obiscura",
 "Espectro Sinistro",
 "Goblin Andarilho",
 "Aranha Mística",
 "Aranha Mortífera",
 "Ogro Vermelho",
 "Sapo Feroz",
 "Fera Gigante",
 "Sereia Encantadora",
 "Troll de Pedra",
 "Lobo Devorador",
 "Guerreiro esqueleto",
 "Zumbi Frenético"]