LISTA_LUGARES = [ 
    "Castelo de Pedras",
    "Planície dos Ventos",
    "Deserto da Perdição",
    "Floresta Congelada do terror",
    "Caverna das Maravilhas",
    "Castelo das Sombras",
    "Planície dos Sonhos",
    "Floresta das Serpentes",
    "Floresta das Fadas",
    "Caverna dos Segredos",
    "Floresta das Ilusões",
    "Planície das Estrelas",
    "Deserto dos Esquecidos",
    "Floresta Congelada dos Encantos",
    "Caverna dos Tesouros",
    "Castelo das Lendas",
    "Floresta Congelada do Yet",
    "Deserto dos Ventos Cortantes"
]