LISTA_LUGARES = [
    "Vila Nova",
    "Cidade dos Ventos",
    "Ruínas de Antares",
    "Ponto do Maré",
    "Caverna das Sombras",
    "Floresta das Lamentações",
    "Mina do Dragão",
    "Lagoa Serena",
    "Monte Celeste",
    "Praia dos Náufragos",
    "Castelo de Pedra",
    "Vale da Lua",
    "Pântano Escuro",
    "Aldeia Escondida",
    "Serra do Sol",
    "Desfiladeiro da Perdição",
    "Cidade das Máscaras",
    "Oásis do Fogo",
    "Ilha dos Piratas",
    "Canyon do Abismo",
    "Planície da Serenidade",
    "Cidade da Neve",
    "Abadia da Luz",
    "Casa das Marés",
    "Castelo de Vidro",
    "Templo da Sabedoria",
    "Praça da Harmonia",
    "Vale dos Anjos",
    "Colina do Dragão",
    "Gruta dos Sonhos",
    "Santuário dos Ventos",
    "Vila do Sol",
    "Torre da Magia",
    "Cidade dos Anões",
    "Aldeia dos Elfos",
    "Vila dos Gnomos",
    "Floresta Encantada",
    "Deserto do Silêncio",
    "Montanha da Perdição",
    "Praia da Lua Cheia",
    "Ruínas de Kalliope",
    "Ilha das Maravilhas",
    "Lagoa das Sereias",
    "Castelo das Sombras",
    "Vila dos Ventos",
    "Cidade das Águas",
    "Caverna da Escuridão",
    "Pico do Vento",
    "Planalto das Estrelas",
    "Aldeia do Arco-Íris",
    "Vale dos Lírios",
    "Praia da Aventura",
    "Castelo de Ferro",
    "Floresta dos Mistérios",
    "Desfiladeiro das Águias",
    "Vila dos Magos",
    "Cidade das Sombras",
    "Santuário da Lua",
    "Ilha do Tesouro",
    "Ponto do Trovão",
    "Ruínas de Érebo",
    "Caverna dos Cristais",
    "Vale dos Ciprestes",
    "Praia do Luar",
    "Monte das Trevas",
    "Torre do Poder",
    "Cidade dos Gigantes",
    "Aldeia das Fadas",
    "Vila dos Lobos",
    "Floresta dos Encantos",
    "Deserto dos Ventos",
    "Pico da Montanha",
    "Planalto das Águias",
    "Vale dos Esquilos",
    "Praia das Conchas",
    "Castelo da Lua",
    "Santuário da Sabedoria",
    "Cidade dos Mercadores",
    "Ilha dos Mistérios",
    "Canyon do Dragão",
    "Ruínas de Thalia",
    "Caverna do Vento",
    "Vila dos Pinheiros",
    "Castelo dos Esquecidos",
    "Ponto da Praia",
]